name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name if different

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v20.12.2' # Specify your Node.js version

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: |
          export CI=false
          yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
